option solver cplexamp;
option omit_zero_rows 1;
option cplex_options 'mipdisplay=2 mipinterval=10 timing=1';

model aerodrome.mod;

let filename := "instances/aerodrome_0.txt";

read N,
start,
finish,
Amin,
Nregions,
{i in 1..N} regions[i],
rmax,
{i in 1..N, k in 1..2} coordonnes[i, k]  < (filename);


for {i in 1..N} {
printf "x[%d] : %d / y[%d] : %d\n", i, coordonnes[i, 1], i, coordonnes[i, 2];
};
